import { createHmac } from "node:crypto";
import { desc, eq } from "drizzle-orm";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { getDb, schema } from "@/lib/db";
import { verifyChain } from "./hash-chain";

function signingSecret(): string {
  const secret = process.env.AUDIT_REPORT_SIGNING_SECRET;
  if (!secret) {
    throw new Error("AUDIT_REPORT_SIGNING_SECRET is not set");
  }
  return secret;
}

type AuditSummary = {
  firmId: string;
  firmName: string;
  generatedAt: string;
  chainValid: boolean;
  entryCount: number;
  tipOrFailure: string;
};

function canonicalizeSummary(summary: AuditSummary): string {
  return JSON.stringify(summary, Object.keys(summary).sort());
}

export function computeAuditSignature(summary: AuditSummary): string {
  return createHmac("sha256", signingSecret()).update(canonicalizeSummary(summary)).digest("hex");
}

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 16 },
  verdict: { fontSize: 12, marginBottom: 16, fontWeight: 700 },
  row: { flexDirection: "row", borderBottom: "1px solid #eee", paddingVertical: 4 },
  headerRow: { flexDirection: "row", borderBottom: "1px solid #000", paddingVertical: 4, fontWeight: 700 },
  cellSeq: { width: 30 },
  cellCategory: { width: 100 },
  cellOutcome: { width: 70 },
  cellClient: { width: 100 },
  cellHash: { flex: 1, fontSize: 7 },
  footer: { marginTop: 24, fontSize: 8, color: "#666" },
});

function AuditReportDocument({
  summary,
  signature,
  entries,
}: {
  summary: AuditSummary;
  signature: string;
  entries: Array<{
    sequenceNo: number;
    taskCategory: string;
    outcome: string;
    clientReference: string | null;
    entryHash: string;
  }>;
}) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{summary.firmName} — Verification Log Audit Report</Text>
        <Text style={styles.subtitle}>Generated {summary.generatedAt}</Text>
        <Text style={styles.verdict}>
          Chain integrity: {summary.chainValid ? "VALID" : "INVALID"} — {summary.entryCount} entries
        </Text>

        <View style={styles.headerRow}>
          <Text style={styles.cellSeq}>#</Text>
          <Text style={styles.cellCategory}>Task category</Text>
          <Text style={styles.cellOutcome}>Outcome</Text>
          <Text style={styles.cellClient}>Client / engagement</Text>
          <Text style={styles.cellHash}>Entry hash</Text>
        </View>
        {entries.map((e) => (
          <View style={styles.row} key={e.sequenceNo}>
            <Text style={styles.cellSeq}>{e.sequenceNo}</Text>
            <Text style={styles.cellCategory}>{e.taskCategory}</Text>
            <Text style={styles.cellOutcome}>{e.outcome}</Text>
            <Text style={styles.cellClient}>{e.clientReference ?? "—"}</Text>
            <Text style={styles.cellHash}>{e.entryHash}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Integrity verdict: {summary.tipOrFailure}
          {"\n"}
          HMAC-SHA256 signature (over the summary above): {signature}
          {"\n"}
          This signature proves this report was generated by this system and its summary fields were not altered
          after export. It does not itself prove the underlying log entries are accurate — see the hash chain
          verdict above for that.
        </Text>
      </Page>
    </Document>
  );
}

export type GeneratedAuditReport = {
  pdfBuffer: Buffer;
  signature: string;
  chainValid: boolean;
  auditReportExportId: string;
};

/**
 * Generates a signed PDF audit report for a firm's verification log:
 * verifies the hash chain, renders a PDF listing every entry plus the
 * verdict, HMAC-signs a canonical summary of the report, and records the
 * export (audit_report_exports) so there's a record of who exported what and
 * whether the chain was valid at that time.
 */
export async function generateAuditReport(firmId: string, generatedByUserId: string): Promise<GeneratedAuditReport> {
  const db = getDb();

  const [firm] = await db.select().from(schema.firms).where(eq(schema.firms.id, firmId)).limit(1);
  if (!firm) {
    throw new Error(`No firm ${firmId}`);
  }

  const chainResult = await verifyChain(firmId);

  const entries = await db
    .select({
      sequenceNo: schema.verificationLog.sequenceNo,
      taskCategory: schema.verificationLog.taskCategory,
      outcome: schema.verificationLog.outcome,
      clientReference: schema.verificationLog.clientReference,
      entryHash: schema.verificationLog.entryHash,
    })
    .from(schema.verificationLog)
    .where(eq(schema.verificationLog.firmId, firmId))
    .orderBy(desc(schema.verificationLog.sequenceNo));

  const generatedAt = new Date().toISOString();
  const summary: AuditSummary = {
    firmId,
    firmName: firm.name,
    generatedAt,
    chainValid: chainResult.valid,
    entryCount: chainResult.entryCount,
    tipOrFailure: chainResult.valid
      ? `tip=${chainResult.tipHash}`
      : `INVALID at sequence_no=${chainResult.failedAtSequenceNo}: ${chainResult.reason}`,
  };

  const signature = computeAuditSignature(summary);

  const pdfBuffer = await renderToBuffer(
    <AuditReportDocument summary={summary} signature={signature} entries={[...entries].reverse()} />
  );

  const [exportRow] = await db
    .insert(schema.auditReportExports)
    .values({
      firmId,
      chainValid: chainResult.valid,
      signature,
      generatedBy: generatedByUserId,
    })
    .returning();

  return { pdfBuffer, signature, chainValid: chainResult.valid, auditReportExportId: exportRow.id };
}
